services:
  - type: web
    name: eco-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GROQ_API_KEY
        value: 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
    plan: free
